"""Print API-free browser fixtures generated by the real simulator, no user DB.

Run from backend: PYTHONPATH=. .venv/bin/python scripts/export_dinner_qa.py
The caller may save stdout as web/scripts/fixtures/dinner-snapshots.json.
"""
from datetime import datetime, timedelta, timezone
import json

from lingolife import dinner
from lingolife.db import Database
from lingolife.life_service import LifeWorldService

now = datetime(2026, 9, 6, 18, tzinfo=timezone.utc)
service = LifeWorldService(Database("sqlite:///:memory:"), "UTC")
profiles = {"ava":{"name":"Ava","personality":["caring","tidy"],"householdRole":"cook"},
            "bo":{"name":"Bo","personality":["friendly"]}}
entries = [{"id":key,"profile":profile} for key, profile in profiles.items()]
state = service.engine.initialize("isolated-dinner-qa",profiles,{key:{"household_id":"shared","home_location_id":"home-1","current_location_id":"home-1"} for key in profiles},now=now)
for resident in state['residents'].values():
    resident['current_location_id'] = 'home-1'
    resident['runtime']['needs'].update(food=50,rest=80,hygiene=70,comfort=70)
    resident['current_action'].update(action_type='read',status='performing',location_id='home-1',started_at=now.isoformat(),ends_at=(now+timedelta(hours=1)).isoformat())
dinner.propose(state,profiles,'shared',now,'2026-09-06',source='player')
frames = []
previous = None
for seconds in range(0, 15*60+1, 15):
    moment = now+timedelta(seconds=seconds)
    state = service.engine.advance(state,profiles,now=moment)
    service.load = lambda *args, **kwargs: state
    city = service.city('isolated-dinner-qa',entries,now=moment)
    household = city['households'][0]
    signature = (household['life'].get('dinner',{}).get('phase'), tuple((item['id'],item['current_action']['id'],item['current_action']['status']) for item in city['npcs']))
    if signature != previous:
        frames.append({'seconds':seconds,'household':household,'residents':city['npcs']})
        previous = signature
    if household['life'].get('dinner',{}).get('phase') == 'completed':
        break
assert frames[-1]['household']['life']['dinner']['phase']=='completed'
print(json.dumps(frames,ensure_ascii=False,separators=(',',':')))
