import {type FormEvent,useCallback,useEffect,useState} from 'react'
import {adminApi,ApiError,quotaText} from './api'
import type {AdminSummary,AdminUser} from './types'

const date=(value?:string|null)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Never'
export function AdminApp(){
 const [authenticated,setAuthenticated]=useState(false),[checking,setChecking]=useState(true),[password,setPassword]=useState(''),[error,setError]=useState('')
 const [summary,setSummary]=useState<AdminSummary|null>(null),[users,setUsers]=useState<AdminUser[]>([]),[query,setQuery]=useState(''),[invites,setInvites]=useState<string[]>([]),[busy,setBusy]=useState(false)
 const load=useCallback(async(q='')=>{try{const [s,u]=await Promise.all([adminApi.summary(),adminApi.users(q)]);setSummary(s);setUsers(u.users)}catch(cause){if(cause instanceof ApiError&&cause.status===401)setAuthenticated(false);else setError('Could not load admin data.')}},[])
 useEffect(()=>{adminApi.session().then(()=>{setAuthenticated(true);void load()}).catch(()=>setAuthenticated(false)).finally(()=>setChecking(false))},[load])
 const login=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await adminApi.login(password);setPassword('');setAuthenticated(true);await load()}catch{setError('Incorrect password or too many attempts.')}finally{setBusy(false)}}
 const update=async(user:AdminUser,body:{disabled?:boolean;quota_delta?:number})=>{setBusy(true);setError('');try{await adminApi.updateUser(user.id,body);await load(query)}catch{setError('The user could not be updated.')}finally{setBusy(false)}}
 if(checking)return <main className="admin-login"><p>Checking secure session…</p></main>
 if(!authenticated)return <main className="admin-login"><form onSubmit={login}><p className="admin-mark">LL</p><h1>Playtest console</h1><p>Restricted access. The browser keeps the admin session in a secure cookie.</p><label>Admin password<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="gate-error">{error}</p>}<button disabled={busy}>{busy?'Checking…':'Sign in'}</button></form></main>
 return <main className="admin"><nav><div><b>LingoLife</b><span>Playtest console</span></div><button onClick={async()=>{await adminApi.logout();setAuthenticated(false)}}>Sign out</button></nav><section className="admin-body"><header><div><p className="eyebrow">Live overview</p><h1>Early access</h1></div><button onClick={()=>void load(query)}>Refresh</button></header>{error&&<p className="admin-alert">{error}</p>}
 <div className="summary">{([['Users',summary?.total_users],['Active today',summary?.active_today],['AI calls today',summary?.chats_today],['Disabled',summary?.disabled_users]] as const).map(([label,value])=><article key={label}><span>{label}</span><strong>{value??'—'}</strong></article>)}</div>
 <section className="admin-panel"><div className="panel-head"><div><h2>Testers</h2><p>No chat content is shown here.</p></div><form onSubmit={e=>{e.preventDefault();void load(query)}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search username"/><button>Search</button></form></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Last active</th><th>Today</th><th>Status</th><th>Controls</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><b>{user.username}</b><small>#{user.id}</small></td><td>{date(user.last_active_at)}</td><td>{quotaText(user.quota)}</td><td><span className={`tag ${user.disabled?'off':'on'}`}>{user.disabled?'Disabled':'Active'}</span></td><td className="controls"><button disabled={busy} onClick={()=>void update(user,{quota_delta:10})}>+10</button><button disabled={busy} onClick={()=>void update(user,{disabled:!user.disabled})}>{user.disabled?'Enable':'Disable'}</button></td></tr>)}</tbody></table>{!users.length&&<p className="no-data">No users found.</p>}</div></section>
 <section className="admin-panel invite-panel"><div><h2>Create invitations</h2><p>Each code can register one unique username.</p></div><button disabled={busy} onClick={async()=>{setBusy(true);try{const result=await adminApi.invites(5,30);setInvites(result.invites)}catch{setError('Invites could not be created.')}finally{setBusy(false)}}}>Generate 5 codes</button>{invites.length>0&&<div className="invite-list">{invites.map(code=><code key={code}>{code}</code>)}</div>}</section>
 </section></main>
}
