import type {AdminResetOnboardingRequest,AdminResetOnboardingResponse,AdminSummary,AdminUser,AgentState,AgentTrace,AuthResponse,ChatResponse,City,Household,HouseholdsResponse,InvitesResponse,LearningProgress,LifeStoriesResponse,LifeStory,LifeStoryLevel,LifeStoryStatus,MeResponse,NpcEntry,NpcProfile,OnboardingCompleteRequest,OnboardingCompleteResponse,OnboardingState,Quota,Room,SocialAction,SocialInteraction,UnusedInvitesResponse,UsersResponse} from './types'
import type {WorldLayoutDocument,WorldLayoutResponse} from './worldLayout'
const tokenKey='lingolife.session-token'
const randomId=(prefix:string)=>`${prefix}-${crypto.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`}`
export class ApiError extends Error{status:number;code?:string;constructor(status:number,message:string,code?:string){super(message);this.status=status;this.code=code}}
type ValidationIssue={msg?:unknown;loc?:unknown}
const validationMessage=(detail:unknown)=>{
 if(!Array.isArray(detail))return undefined
 const issue=detail.find((value):value is ValidationIssue=>Boolean(value)&&typeof value==='object'&&typeof (value as ValidationIssue).msg==='string')
 if(!issue||typeof issue.msg!=='string')return undefined
 const location=Array.isArray(issue.loc)?issue.loc.map(String).filter(value=>value!=='body').join('.') :''
 return location?`${location}: ${issue.msg}`:issue.msg
}
async function request<T>(path:string,init:RequestInit={},admin=false):Promise<T>{
 const token=session.token();const headers=new Headers(init.headers);if(token&&!admin)headers.set('Authorization',`Bearer ${token}`)
 const response=await fetch(`/api/v1${path}`,{...init,headers,credentials:admin?'include':'same-origin'});const data=await response.json().catch(()=>null)
 if(!response.ok){const detail=data?.error??data?.detail;const message=typeof detail==='string'?detail:detail?.message??validationMessage(detail);throw new ApiError(response.status,message||data?.message||'Request failed',detail?.code)}
 return data as T
}
async function streamChat(message:string,key:string,npc_id:string,onDelta:(chunk:string)=>void):Promise<ChatResponse>{
 const headers=new Headers({'Content-Type':'application/json','Idempotency-Key':key});const token=session.token();if(token)headers.set('Authorization',`Bearer ${token}`)
 const response=await fetch('/api/v1/chat/stream',{method:'POST',headers,body:JSON.stringify({message,npc_id})})
 if(!response.ok){const data=await response.json().catch(()=>null);throw new ApiError(response.status,data?.error?.message||'Request failed',data?.error?.code)}
 if(!response.body)throw new ApiError(502,'Streaming response is unavailable')
 const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',final:ChatResponse|null=null
 while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line)continue;const event=JSON.parse(line);if(event.type==='delta')onDelta(event.data);else if(event.type==='final')final=event.data;else if(event.type==='error')throw new ApiError(502,event.data?.message||'Stream interrupted')}if(done)break}
 if(!final)throw new ApiError(502,'Stream ended before the final result');return final
}
export const session={
 token:()=>{try{return localStorage.getItem(tokenKey)}catch{return null}},
 save:(token:string)=>{try{localStorage.setItem(tokenKey,token)}catch{throw new ApiError(503,'This browser cannot save the login session.')}},
 clear:()=>{try{localStorage.removeItem(tokenKey)}catch{/* storage can be unavailable */}},
}
const json=(value:unknown):RequestInit=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)})
export type WorldRequestOptions={signal?:AbortSignal}
export type LifeStoryQuery={level?:LifeStoryLevel;status?:LifeStoryStatus;npc_id?:string;household_id?:string;game_date?:string}
const query=(values:Record<string,string|undefined>)=>{const params=new URLSearchParams();Object.entries(values).forEach(([key,value])=>{if(value)params.set(key,value)});const encoded=params.toString();return encoded?`?${encoded}`:''}
export const api={register:(username:string,password:string,invite_code:string)=>request<AuthResponse>('/auth/register',json({username,password,invite_code})),login:(username:string,password:string)=>request<AuthResponse>('/auth/login',json({username,password})),setPassword:(new_password:string,current_password?:string)=>request<{has_password:boolean}>('/auth/password',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({new_password,current_password:current_password||null})}),me:()=>request<MeResponse>('/auth/me'),logout:()=>request<void>('/auth/logout',{method:'POST'}),onboarding:()=>request<OnboardingState>('/onboarding'),completeOnboarding:(body:OnboardingCompleteRequest)=>request<OnboardingCompleteResponse>('/onboarding/complete',json(body)),worldLayout:()=>request<WorldLayoutResponse>('/world-layout'),city:()=>request<City>('/city'),world:(options:WorldRequestOptions={})=>request<City>('/world',{signal:options.signal}),socialEvents:()=>request<{social_interactions:SocialInteraction[]}>('/social-events'),observeSocial:(id:string)=>request<SocialInteraction>(`/social-events/${encodeURIComponent(id)}/observe`,{method:'POST'}),interveneSocial:(id:string,action:SocialAction)=>request<SocialInteraction>(`/social-events/${encodeURIComponent(id)}/intervene`,json({action})),lifeStories:(filters:LifeStoryQuery={})=>request<LifeStoriesResponse>(`/life-stories${query(filters)}`),observeLifeStory:(id:string)=>request<LifeStory>(`/life-stories/${encodeURIComponent(id)}/observe`,{method:'POST'}),interveneLifeStory:(id:string,action:string,idempotency_key:string)=>request<LifeStory>(`/life-stories/${encodeURIComponent(id)}/intervene`,json({action,idempotency_key})),households:()=>request<HouseholdsResponse>('/households'),household:(id:string)=>request<Household>(`/households/${encodeURIComponent(id)}`),room:(npc_id='emma')=>request<Room>(`/room?npc_id=${encodeURIComponent(npc_id)}`),chat:(message:string,key:string,npc_id='emma')=>request<ChatResponse>('/chat',{...json({message,npc_id}),headers:{'Content-Type':'application/json','Idempotency-Key':key}}),chatStream:streamChat,npcs:()=>request<{npcs:NpcEntry[];limit:number}>('/npcs'),createNpc:(profile:NpcProfile)=>request<NpcEntry>('/npcs',json(profile)),saveNpc:(id:string,profile:NpcProfile)=>request<NpcEntry>(`/npcs/${encodeURIComponent(id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}),npcProfile:()=>request<NpcProfile>('/npc/profile'),saveNpcProfile:(profile:NpcProfile)=>request<NpcProfile>('/npc/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}),npcAgent:(id:string)=>request<AgentState>(`/npcs/${encodeURIComponent(id)}/agent`),deleteNpcMemory:(id:string,memoryId:number)=>request<void>(`/npcs/${encodeURIComponent(id)}/memories/${memoryId}`,{method:'DELETE'}),learningProfile:()=>request<LearningProgress>('/learning/profile'),key:()=>randomId('chat')}
export const adminApi={login:(password:string)=>request<void>('/admin/login',json({password}),true),session:()=>request<{authenticated:boolean}>('/admin/session',{},true),logout:()=>request<void>('/admin/logout',{method:'POST'},true),summary:()=>request<AdminSummary>('/admin/summary',{},true),users:(q='')=>request<UsersResponse>(`/admin/users?q=${encodeURIComponent(q)}`,{},true),agentTraces:(limit=100)=>request<{traces:AgentTrace[]}>(`/admin/agent-traces?limit=${limit}`,{},true),worldLayout:()=>request<WorldLayoutResponse>('/admin/world-layout',{},true),saveWorldLayout:(layout:WorldLayoutDocument)=>request<WorldLayoutResponse>('/admin/world-layout',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({layout})},true),resetWorldLayout:()=>request<WorldLayoutResponse>('/admin/world-layout/reset',{method:'POST'},true),updateUser:(id:string|number,body:{disabled?:boolean;quota_delta?:number})=>request<AdminUser>(`/admin/users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},true),resetOnboarding:(id:string|number,body:AdminResetOnboardingRequest)=>request<AdminResetOnboardingResponse>(`/admin/users/${id}/reset-onboarding`,json(body),true),invites:(count:number,daily_quota:number)=>request<InvitesResponse>('/admin/invites',json({count,daily_quota}),true),unusedInvites:()=>request<UnusedInvitesResponse>('/admin/invites',{},true)}
export const quotaText=(quota:Quota|null)=>quota?`${quota.remaining} messages left${quota.bonus_credits?` · ${quota.bonus_credits} bonus`:''}`:'—'
