import type {AdminSummary,AdminUser,AgentState,AgentTrace,AuthResponse,ChatResponse,City,InvitesResponse,LearningProgress,MeResponse,NpcEntry,NpcProfile,Quota,Room,SocialAction,SocialInteraction,UnusedInvitesResponse,UsersResponse} from './types'
const tokenKey='lingolife.session-token'
const randomId=(prefix:string)=>`${prefix}-${crypto.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`}`
export class ApiError extends Error{status:number;code?:string;constructor(status:number,message:string,code?:string){super(message);this.status=status;this.code=code}}
async function request<T>(path:string,init:RequestInit={},admin=false):Promise<T>{
 const token=session.token();const headers=new Headers(init.headers);if(token&&!admin)headers.set('Authorization',`Bearer ${token}`)
 const response=await fetch(`/api/v1${path}`,{...init,headers,credentials:admin?'include':'same-origin'});const data=await response.json().catch(()=>null)
 if(!response.ok)throw new ApiError(response.status,data?.error?.message||data?.detail||'Request failed',data?.error?.code)
 return data as T
}
async function streamChat(message:string,key:string,npc_id:string,onDelta:(chunk:string)=>void):Promise<ChatResponse>{
 const headers=new Headers({'Content-Type':'application/json','Idempotency-Key':key});const token=session.token();if(token)headers.set('Authorization',`Bearer ${token}`)
 const response=await fetch('/api/v1/chat/stream',{method:'POST',headers,body:JSON.stringify({message,npc_id})})
 if(!response.ok){const data=await response.json().catch(()=>null);throw new ApiError(response.status,data?.error?.message||'Request failed',data?.error?.code)}
 if(!response.body)throw new ApiError(502,'Streaming response is unavailable')
 const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',final:ChatResponse|null=null
 while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line)continue;const event=JSON.parse(line);if(event.type==='delta')onDelta(event.data);else if(event.type==='final')final=event.data;else if(event.type==='error')throw new ApiError(502,event.data?.message||'Stream interrupted')}if(done)break}
 if(!final)throw new ApiError(502,'Stream ended before the final result');return final
}
export const session={
 token:()=>{try{return localStorage.getItem(tokenKey)}catch{return null}},
 save:(token:string)=>{try{localStorage.setItem(tokenKey,token)}catch{throw new ApiError(503,'This browser cannot save the login session.')}},
 clear:()=>{try{localStorage.removeItem(tokenKey)}catch{/* storage can be unavailable */}},
}
const json=(value:unknown):RequestInit=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)})
export const api={register:(username:string,password:string,invite_code:string)=>request<AuthResponse>('/auth/register',json({username,password,invite_code})),login:(username:string,password:string)=>request<AuthResponse>('/auth/login',json({username,password})),setPassword:(new_password:string,current_password?:string)=>request<{has_password:boolean}>('/auth/password',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({new_password,current_password:current_password||null})}),me:()=>request<MeResponse>('/auth/me'),logout:()=>request<void>('/auth/logout',{method:'POST'}),city:()=>request<City>('/city'),world:()=>request<City>('/world'),socialEvents:()=>request<{social_interactions:SocialInteraction[]}>('/social-events'),interveneSocial:(id:string,action:SocialAction)=>request<SocialInteraction>(`/social-events/${encodeURIComponent(id)}/intervene`,json({action})),room:(npc_id='emma')=>request<Room>(`/room?npc_id=${encodeURIComponent(npc_id)}`),chat:(message:string,key:string,npc_id='emma')=>request<ChatResponse>('/chat',{...json({message,npc_id}),headers:{'Content-Type':'application/json','Idempotency-Key':key}}),chatStream:streamChat,npcs:()=>request<{npcs:NpcEntry[];limit:number}>('/npcs'),createNpc:(profile:NpcProfile)=>request<NpcEntry>('/npcs',json(profile)),saveNpc:(id:string,profile:NpcProfile)=>request<NpcEntry>(`/npcs/${encodeURIComponent(id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}),npcProfile:()=>request<NpcProfile>('/npc/profile'),saveNpcProfile:(profile:NpcProfile)=>request<NpcProfile>('/npc/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}),npcAgent:(id:string)=>request<AgentState>(`/npcs/${encodeURIComponent(id)}/agent`),deleteNpcMemory:(id:string,memoryId:number)=>request<void>(`/npcs/${encodeURIComponent(id)}/memories/${memoryId}`,{method:'DELETE'}),learningProfile:()=>request<LearningProgress>('/learning/profile'),key:()=>randomId('chat')}
export const adminApi={login:(password:string)=>request<void>('/admin/login',json({password}),true),session:()=>request<{authenticated:boolean}>('/admin/session',{},true),logout:()=>request<void>('/admin/logout',{method:'POST'},true),summary:()=>request<AdminSummary>('/admin/summary',{},true),users:(q='')=>request<UsersResponse>(`/admin/users?q=${encodeURIComponent(q)}`,{},true),agentTraces:(limit=100)=>request<{traces:AgentTrace[]}>(`/admin/agent-traces?limit=${limit}`,{},true),updateUser:(id:string|number,body:{disabled?:boolean;quota_delta?:number})=>request<AdminUser>(`/admin/users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},true),invites:(count:number,daily_quota:number)=>request<InvitesResponse>('/admin/invites',json({count,daily_quota}),true),unusedInvites:()=>request<UnusedInvitesResponse>('/admin/invites',{},true)}
export const quotaText=(quota:Quota|null)=>quota?`${quota.remaining} messages left${quota.bonus_credits?` · ${quota.bonus_credits} bonus`:''}`:'—'
