import {type FormEvent,type KeyboardEvent,useEffect,useRef,useState} from 'react'
import {AnimatePresence,motion,useReducedMotion} from 'motion/react'
import {ApiError,api,session} from './api'
import {AvatarStage} from './components/AvatarStage'
import {defaultAvatar} from './avatar'
import {CharacterStudio} from './components/CharacterStudio'
import {EventCard} from './components/EventCard'
import {LearningPanel} from './components/LearningPanel'
import {StatBar} from './components/StatBar'
import {CityMap,type CityCharacter,type CityLandmark} from './components/CityMap'
import {SettingsPanel} from './components/SettingsPanel'
import {ConversationEntrance} from './components/ConversationEntrance'
import {useLanguage} from './i18n'
import './ConversationRefinements.css'
import './ExperienceTransitions.css'
import type {ActiveEvent,City,EventUpdate,Feedback,LearningProgress,Message,Mood,NpcEntry,NpcProfile,Quota,Stats,User} from './types'
type Pending={message:string;key:string}
const initialProfile:NpcProfile={name:'Emma',relationship:'Friend',personality:['kind','thoughtful','quiet'],interests:['art','music','photography'],occupation:'Designer',longTermGoal:'Open a small independent design studio.',avatar:defaultAvatar}
const cityPlaceZh:Record<string,string>={central_station:'中央车站',north_bus_terminal:'北门客运站',airport_express:'机场快线站',business_center:'商务中心',innovation_hub:'创新中心',design_studio:'运河设计工作室',city_hospital:'市立医院',neighborhood_clinic:'社区诊所',animal_shelter:'城市动物救助站',riverside_park:'河畔公园',botanical_garden:'植物园',hilltop_park:'山顶公园',police_station:'警察局',city_hall:'市政厅',fire_station:'消防站',community_center:'社区活动中心',old_town_market:'老城市场',harbor_mall:'港湾商场',maple_bookshop:'枫叶书店',moonlight_cafe:'月光咖啡馆',garden_cafe:'花园咖啡馆',harbor_restaurant:'港湾餐厅',community_gallery:'社区画廊',city_museum:'城市博物馆',aurora_theater:'极光剧院',music_hall:'南岸音乐厅',city_library:'城市图书馆',community_school:'社区学校',city_university:'城市大学',sunny_plaza:'阳光广场',canal_square:'运河广场',greenway_gym:'绿道健身房',city_stadium:'城市体育场',canal_walk:'运河步道',south_harbor:'南岸港口',co_working_loft:'老城共享办公阁楼'}
export default function App({user,initialQuota,onLogout}:{user:User;initialQuota:Quota;onLogout:()=>void}){
 const {language,t}=useLanguage(),zh=language==='zh'
 const reduce=useReducedMotion(),[stats,setStats]=useState<Stats|null>(null),[mood,setMood]=useState<Mood>('sad'),[messages,setMessages]=useState<Message[]>([]),[feedback,setFeedback]=useState<Feedback|null>(null),[text,setText]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Pending|null>(null),log=useRef<HTMLDivElement>(null)
 const [quota,setQuota]=useState(initialQuota)
 const [profile,setProfile]=useState<NpcProfile>(initialProfile),[studio,setStudio]=useState(false),[savingProfile,setSavingProfile]=useState(false),[profileError,setProfileError]=useState('')
 const [npcs,setNpcs]=useState<NpcEntry[]>([]),[npcId,setNpcId]=useState(localStorage.getItem('lingolife.npc-id')||'emma'),[creating,setCreating]=useState(false)
 const [city,setCity]=useState<City|null>(null),[view,setView]=useState<'city'|'chat'>('city'),[settingsOpen,setSettingsOpen]=useState(false)
 const [entranceKey,setEntranceKey]=useState(0),[entranceVisible,setEntranceVisible]=useState(false)
 const [hasPassword,setHasPassword]=useState(Boolean(user.has_password))
 const [activeEvent,setActiveEvent]=useState<ActiveEvent|null>(null),[eventUpdate,setEventUpdate]=useState<EventUpdate|null>(null),[learning,setLearning]=useState<LearningProgress|null>(null),[learningOpen,setLearningOpen]=useState(false)
 const [showOlder,setShowOlder]=useState(false)
 const fail=(cause:unknown,fallback:string)=>{if(cause instanceof ApiError&&(cause.status===401||cause.status===403)){session.clear();onLogout();return}if(cause instanceof ApiError&&cause.code==='RATE_LIMITED')setError(t('chat.rateLimited'));else if(cause instanceof ApiError&&cause.status===429)setError(t('chat.quotaReached'));else setError(fallback)}
 const loadNpc=async(id:string,entries?:NpcEntry[])=>{setError('');setReady(false);setShowOlder(false);try{const list=entries||npcs;const chosen=list.find(x=>x.id===id)||list[0];if(!chosen)throw new Error('No character');const room=await api.room(chosen.id);setNpcId(chosen.id);localStorage.setItem('lingolife.npc-id',chosen.id);setProfile(chosen.profile);setStats(room.stats);setMood(room.npc.animation);setMessages(room.messages);setActiveEvent(room.active_event||null);setEventUpdate(null);setFeedback(null);if(room.quota)setQuota(room.quota);setReady(true);return room}catch(cause){fail(cause,zh?'无法打开房间，请检查网络后重试。':"Couldn't open the room. Check your connection and try again.");return null}}
 const load=async()=>{try{const [data,cityData]=await Promise.all([api.npcs(),api.city()]);setNpcs(data.npcs);setCity(cityData);const id=data.npcs.some(x=>x.id===npcId)?npcId:data.npcs[0]?.id||'emma';await loadNpc(id,data.npcs);void api.learningProfile().then(setLearning).catch(()=>undefined)}catch(cause){fail(cause,t('character.loadError'))}}
 // The room is loaded once per authenticated mount; retries call load explicitly.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void load()},[])
 useEffect(()=>{log.current?.scrollTo({top:log.current.scrollHeight,behavior:reduce?'auto':'smooth'})},[messages,busy,reduce])
 const send=async(request:Pending)=>{setBusy(true);setError('');setMessages(old=>[...old,{speaker:'npc',text:''}]);try{const result=await api.chatStream(request.message,request.key,npcId,chunk=>setMessages(old=>old.map((item,index)=>index===old.length-1&&item.speaker==='npc'?{...item,text:item.text+chunk}:item)));setMessages(old=>old.map((item,index)=>index===old.length-1&&item.speaker==='npc'?{...item,text:result.npc_reply}:item));setStats(result.stats);setMood(result.animation);setFeedback(result.english_feedback);if(result.quota)setQuota(result.quota);if(result.event_update)setEventUpdate(result.event_update);if('active_event'in result)setActiveEvent(result.active_event||null);if(result.learning_summary)setLearning(result.learning_summary);setPending(null);setText('')}catch(cause){setMessages(old=>old.slice(0,-1));fail(cause,zh?'回复中断了，你的消息仍保留着，请重试。':'The reply was interrupted. Your message is safe — try again.')}finally{setBusy(false)}}
 const submit=(event:FormEvent)=>{event.preventDefault();const message=text.trim();if(!message||busy||pending||!ready)return;const request={message,key:api.key()};setPending(request);setMessages(old=>[...old,{speaker:'player',text:message}]);void send(request)}
 const keyDown=(event:KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();event.currentTarget.form?.requestSubmit()}}
 const saveProfile=async()=>{setSavingProfile(true);setProfileError('');const wasCreating=creating;try{const saved=creating?await api.createNpc({...profile,avatar:{...profile.avatar,strokes:[]}}):await api.saveNpc(npcId,{...profile,avatar:{...profile.avatar,strokes:[]}});const [data,cityData]=await Promise.all([api.npcs(),api.city()]);setNpcs(data.npcs);setCity(cityData);setCreating(false);setStudio(false);await loadNpc(saved.id,data.npcs);if(wasCreating)setView('city')}catch(cause){setProfileError(cause instanceof ApiError&&cause.code==='NPC_LIMIT_REACHED'?t('character.limit'):t('character.saveError'))}finally{setSavingProfile(false)}}
 const beginCreate=()=>{setCreating(true);setProfile({...initialProfile,name:t('character.newName'),avatar:{...defaultAvatar,strokes:[]}});setStudio(true)}
 const cityCharacters:CityCharacter[]=(city?.npcs||[]).map(resident=>{const location=city?.locations.find(item=>item.id===resident.current_location_id);return {id:resident.id,name:resident.name,avatar:resident.avatar,home:{x:resident.home.x*1200/(city?.map.width||1600),y:resident.home.y*760/(city?.map.height||1000)},location:{x:resident.position.x*1200/(city?.map.width||1600),y:resident.position.y*760/(city?.map.height||1000),place:resident.is_home?t('map.location.home'):language==='zh'?(cityPlaceZh[location?.id||'']||location?.name||t('map.currentLocation')):(location?.name||t('map.currentLocation'))}}})
 const cityLandmarks:CityLandmark[]=(city?.locations||[]).map(location=>({id:location.id,name:language==='zh'?(cityPlaceZh[location.id]||location.name):location.name,kind:location.kind,x:location.x*1200/(city?.map.width||1600),y:location.y*760/(city?.map.height||1000)}))
 const currentResident=city?.npcs.find(resident=>resident.id===npcId),currentLocation=city?.locations.find(location=>location.id===currentResident?.current_location_id)
 const currentPlace=currentResident?.is_home?t('map.home',{name:profile.name}):language==='zh'?(cityPlaceZh[currentLocation?.id||'']||currentLocation?.name||t('map.currentLocation')):(currentLocation?.name||t('map.currentLocation'))
 const isToday=(value?:string)=>{if(!value)return true;const parsed=new Date(value.includes('T')?value:`${value.replace(' ','T')}Z`),now=new Date();return parsed.getFullYear()===now.getFullYear()&&parsed.getMonth()===now.getMonth()&&parsed.getDate()===now.getDate()}
 const olderCount=messages.filter(message=>!isToday(message.created_at)).length,visibleMessages=showOlder?messages:messages.filter(message=>isToday(message.created_at))
 const latestNpcLine=[...messages].reverse().find(message=>message.speaker==='npc'&&message.text.trim())?.text||'',entranceLine=activeEvent?.stage.prompt||latestNpcLine,entranceActive=entranceVisible&&Boolean(entranceLine)
 const overlays=<AnimatePresence>{studio&&<motion.div key="studio" className="experience-overlay-layer" initial={reduce?false:{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><CharacterStudio language={language} profile={profile} onChange={setProfile} onSave={()=>void saveProfile()} onClose={()=>{setStudio(false);if(creating){setCreating(false);const current=npcs.find(x=>x.id===npcId);if(current)setProfile(current.profile)}}} saving={savingProfile} error={profileError}/></motion.div>} {learningOpen&&<motion.div key="learning" className="experience-overlay-layer" initial={reduce?false:{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><LearningPanel progress={learning} onClose={()=>setLearningOpen(false)}/></motion.div>} {settingsOpen&&<motion.div key="settings" className="experience-overlay-layer" initial={reduce?false:{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><SettingsPanel hasPassword={hasPassword} onPasswordSet={()=>setHasPassword(true)} onClose={()=>setSettingsOpen(false)}/></motion.div>}</AnimatePresence>
 const cityView=<motion.main key="city" className="city-shell experience-view" initial={reduce?false:{opacity:0,scale:.992,filter:'blur(4px)'}} animate={{opacity:1,scale:1,filter:'blur(0px)'}} exit={reduce?{opacity:0}:{opacity:0,scale:1.012,filter:'blur(5px)'}} transition={{duration:reduce?0:.3,ease:[.22,.8,.25,1]}}><section className="city-screen"><header className="city-header"><div><p className="eyebrow">LingoLife</p><h1>{t('map.title')}</h1><span>{t('map.subtitle')}</span></div><div className="city-actions"><button disabled={npcs.length>=5} onClick={beginCreate}>＋ {t('nav.newCharacter')}</button><button onClick={()=>setLearningOpen(true)}>◒ {t('nav.progress')}</button><button onClick={()=>setSettingsOpen(true)}>⚙ {t('nav.settings')}</button><span><b>{user.username}</b><small>{t('nav.quota',{count:quota.remaining})}</small></span><button onClick={async()=>{try{await api.logout()}finally{session.clear();onLogout()}}}>{t('nav.logout')}</button></div></header>{city?<CityMap characters={cityCharacters} landmarks={cityLandmarks} activeCharacterId={npcId} language={language} onCharacterClick={async id=>{const room=await loadNpc(id);if(!room)return;setEntranceKey(value=>value+1);setEntranceVisible(true);setView('chat')}}/>:<p className="city-loading">{t('common.loading')}</p>}</section></motion.main>
 const chatView=<motion.main key="chat" className="shell experience-view" initial={reduce?false:{opacity:0,scale:.985,x:18}} animate={{opacity:1,scale:1,x:0}} exit={reduce?{opacity:0}:{opacity:0,scale:.99,x:24}} transition={{duration:reduce?0:.34,ease:[.22,.8,.25,1]}}><section className="room">
  <header><div><button className="back-city" onClick={async()=>{setEntranceVisible(false);setView('city');setCity(await api.city())}}>← {t('map.back')}</button><p className="room-location">⌖ {currentPlace}</p></div><div className="account"><select className="npc-switch" value={npcId} disabled={busy} onChange={e=>void (async()=>{const room=await loadNpc(e.target.value);if(room){setEntranceKey(value=>value+1);setEntranceVisible(true)}})()} aria-label={t('nav.switchCharacter')}>{npcs.map(x=><option key={x.id} value={x.id}>{x.profile.name}</option>)}</select><button className="learn-button" onClick={()=>setLearningOpen(true)}>◒ {t('nav.progress')}</button><button onClick={()=>setSettingsOpen(true)}>⚙ {t('nav.settings')}</button><span><b>{user.username}</b><small>{t('nav.quota',{count:quota.remaining})}</small></span></div></header>
  <StatBar stats={stats}/><div className="character-stage"><AvatarStage mood={mood} avatar={profile.avatar}/><button className="character-edit-button" onClick={()=>{setCreating(false);setStudio(true)}}>✦ {t('nav.customize')}</button></div>
  <section className="conversation" aria-label={`Conversation with ${profile.name}`}><AnimatePresence initial={false}>{!entranceActive&&<motion.div className="event-reveal" initial={reduce?false:{opacity:0,y:-10,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0}} transition={{type:'spring',stiffness:250,damping:25}}><EventCard language={language} event={activeEvent} update={eventUpdate}/></motion.div>}</AnimatePresence><div className="messages" ref={log} role="log" aria-live="polite">
   {!ready&&!error&&<p className="empty">{t('room.opening')}</p>}
   {olderCount>0&&<button className="older-messages" onClick={()=>setShowOlder(value=>!value)}>{showOlder?t('chat.hideHistory'):t('chat.showHistory',{count:olderCount})}</button>}
   <AnimatePresence initial={false}>{visibleMessages.map((item,index)=><motion.article className={`message ${item.speaker}`} key={`${item.created_at||'new'}-${index}`} initial={reduce?false:{opacity:0,y:12,scale:.98}} animate={{opacity:1,y:0,scale:1}}>{item.speaker==='npc'&&<span className="avatar" aria-hidden>{profile.name[0]||'N'}</span>}<div className="bubble">{item.speaker==='npc'&&<b>{profile.name}</b>}<p>{item.text}</p>{busy&&index===visibleMessages.length-1&&!item.text&&<span className="typing" aria-label={`${profile.name} is typing`}><i/><i/><i/></span>}</div></motion.article>)}</AnimatePresence>
  </div>
  <AnimatePresence>{feedback&&<motion.aside className="feedback" initial={reduce?false:{opacity:0,y:8,height:0}} animate={{opacity:1,y:0,height:'auto'}} exit={{opacity:0,height:0}}><div><strong>✦ {zh?'英语提示':'English note'}</strong><button onClick={()=>setFeedback(null)} aria-label="关闭英语反馈">×</button></div><p>{feedback.tip}</p>{feedback.corrected_text&&<small>{zh?'建议表达':'Try'}: “{feedback.corrected_text}”</small>}</motion.aside>}</AnimatePresence>
  <AnimatePresence>{error&&<motion.div className="error" role="alert" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><span>{error}</span><button onClick={()=>pending?void send(pending):void load()}>{t('common.retry')}</button></motion.div>}</AnimatePresence>
  <form onSubmit={submit}><label className="sr-only" htmlFor="message">Write an English reply</label><textarea id="message" maxLength={500} rows={1} value={text} onChange={e=>setText(e.target.value)} onKeyDown={keyDown} placeholder={zh?`用英语和 ${profile.name} 聊聊…`:`Say something to ${profile.name}…`} disabled={!ready||busy||!!pending}/><motion.button type="submit" disabled={!ready||busy||!!pending||!text.trim()} whileHover={reduce?undefined:{y:-2}} whileTap={reduce?undefined:{scale:.94}}>{busy?<span className="spinner"/>:(zh?'发送':'Send')}</motion.button><small>{zh?'Enter 发送 · Shift+Enter 换行':'Enter to send · Shift+Enter for a new line'}</small></form>
  </section>
  <AnimatePresence>{entranceActive&&<ConversationEntrance key={`${npcId}-${entranceKey}`} name={profile.name} line={entranceLine} place={currentPlace} avatar={profile.avatar} mood={mood} onComplete={()=>setEntranceVisible(false)}/>}</AnimatePresence>
 </section></motion.main>
 return <><AnimatePresence mode="wait" initial={false}>{view==='city'?cityView:chatView}</AnimatePresence>{overlays}</>
}
