import {type FormEvent,type KeyboardEvent,useEffect,useRef,useState} from 'react'
import {AnimatePresence,motion,useReducedMotion} from 'motion/react'
import {ApiError,api,quotaText,session} from './api'
import {AvatarStage} from './components/AvatarStage'
import {defaultAvatar} from './avatar'
import {CharacterStudio} from './components/CharacterStudio'
import {EventCard} from './components/EventCard'
import {LearningPanel} from './components/LearningPanel'
import {StatBar} from './components/StatBar'
import type {ActiveEvent,EventUpdate,Feedback,LearningProgress,Message,Mood,NpcProfile,Quota,Stats,User} from './types'
type Pending={message:string;key:string}
const initialProfile:NpcProfile={name:'Emma',relationship:'Friend',personality:['kind','thoughtful','quiet'],interests:['art','music','photography'],occupation:'Designer',longTermGoal:'Open a small independent design studio.',avatar:defaultAvatar}
export default function App({user,initialQuota,onLogout}:{user:User;initialQuota:Quota;onLogout:()=>void}){
 const reduce=useReducedMotion(),[stats,setStats]=useState<Stats|null>(null),[mood,setMood]=useState<Mood>('sad'),[messages,setMessages]=useState<Message[]>([]),[feedback,setFeedback]=useState<Feedback|null>(null),[text,setText]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Pending|null>(null),log=useRef<HTMLDivElement>(null)
 const [quota,setQuota]=useState(initialQuota)
 const [profile,setProfile]=useState<NpcProfile>(initialProfile),[studio,setStudio]=useState(false),[savingProfile,setSavingProfile]=useState(false),[profileError,setProfileError]=useState('')
 const [activeEvent,setActiveEvent]=useState<ActiveEvent|null>(null),[eventUpdate,setEventUpdate]=useState<EventUpdate|null>(null),[learning,setLearning]=useState<LearningProgress|null>(null),[learningOpen,setLearningOpen]=useState(false)
 const fail=(cause:unknown,fallback:string)=>{if(cause instanceof ApiError&&(cause.status===401||cause.status===403)){session.clear();onLogout();return}if(cause instanceof ApiError&&cause.code==='RATE_LIMITED')setError("You're sending messages quickly. Wait a minute, then try again.");else if(cause instanceof ApiError&&cause.status===429)setError("You've used today's messages. Come back tomorrow to continue with Emma.");else setError(fallback)}
 const load=async()=>{setError('');try{const room=await api.room();setStats(room.stats);setMood(room.npc.animation);setMessages(room.messages);setActiveEvent(room.active_event||null);if(room.quota)setQuota(room.quota);setReady(true);void api.learningProfile().then(setLearning).catch(()=>undefined);try{setProfile(await api.npcProfile())}catch{const saved=localStorage.getItem('lingolife.npc-profile');if(saved)try{setProfile(JSON.parse(saved) as NpcProfile)}catch{/* Ignore an invalid legacy draft. */}}}catch(cause){fail(cause,"Couldn't open the room. Check your connection and try again.");setReady(false)}}
 // The room is loaded once per authenticated mount; retries call load explicitly.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void load()},[])
 useEffect(()=>{log.current?.scrollTo({top:log.current.scrollHeight,behavior:reduce?'auto':'smooth'})},[messages,busy,reduce])
 const send=async(request:Pending)=>{setBusy(true);setError('');try{const result=await api.chat(request.message,request.key);setMessages(old=>[...old,{speaker:'npc',text:result.npc_reply}]);setStats(result.stats);setMood(result.animation);setFeedback(result.english_feedback);if(result.quota)setQuota(result.quota);if(result.event_update)setEventUpdate(result.event_update);if('active_event'in result)setActiveEvent(result.active_event||null);if(result.learning_summary)setLearning(result.learning_summary);setPending(null);setText('')}catch(cause){fail(cause,'The reply was interrupted. Your message is safe — try again.')}finally{setBusy(false)}}
 const submit=(event:FormEvent)=>{event.preventDefault();const message=text.trim();if(!message||busy||pending||!ready)return;const request={message,key:api.key()};setPending(request);setMessages(old=>[...old,{speaker:'player',text:message}]);void send(request)}
 const keyDown=(event:KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();event.currentTarget.form?.requestSubmit()}}
 const saveProfile=async()=>{setSavingProfile(true);setProfileError('');localStorage.setItem('lingolife.npc-profile',JSON.stringify(profile));try{setProfile(await api.saveNpcProfile(profile));setStudio(false)}catch(cause){if(cause instanceof ApiError&&(cause.status===404||cause.status===405)){setProfileError('Saved on this device. Cloud character sync will activate with the NPC Agent service.')}else setProfileError('Could not sync this character. Your local draft is safe.')}finally{setSavingProfile(false)}}
 return <main className="shell"><motion.section className="room" initial={reduce?false:{opacity:0,y:12}} animate={{opacity:1,y:0}}>
  <header><div><p className="eyebrow">{profile.name}'s room</p><h1>{activeEvent?.title||'A quiet evening'}</h1></div><div className="account"><button className="learn-button" onClick={()=>setLearningOpen(true)}>◒ Progress</button><button className="create-button" onClick={()=>setStudio(true)}>✦ Customize</button><span><b>{user.username}</b><small>{quotaText(quota)}</small></span><button onClick={async()=>{try{await api.logout()}finally{session.clear();onLogout()}}}>Exit</button></div></header>
  <StatBar stats={stats}/><AvatarStage mood={mood} avatar={profile.avatar}/>
  <section className="conversation" aria-label={`Conversation with ${profile.name}`}><EventCard event={activeEvent} update={eventUpdate}/><div className="messages" ref={log} role="log" aria-live="polite">
   {!ready&&!error&&<p className="empty">Opening the door…</p>}
   <AnimatePresence initial={false}>{messages.map((item,index)=><motion.article className={`message ${item.speaker}`} key={`${index}-${item.text}`} initial={reduce?false:{opacity:0,y:12,scale:.98}} animate={{opacity:1,y:0,scale:1}}>{item.speaker==='npc'&&<span className="avatar" aria-hidden>{profile.name[0]||'N'}</span>}<div className="bubble">{item.speaker==='npc'&&<b>{profile.name}</b>}<p>{item.text}</p></div></motion.article>)}</AnimatePresence>
   {busy&&<motion.article className="message npc" initial={{opacity:0}} animate={{opacity:1}}><span className="avatar" aria-hidden>{profile.name[0]||'N'}</span><div className="bubble typing" aria-label={`${profile.name} is typing`}><i/><i/><i/></div></motion.article>}
  </div>
  <AnimatePresence>{feedback&&<motion.aside className="feedback" initial={reduce?false:{opacity:0,y:8,height:0}} animate={{opacity:1,y:0,height:'auto'}} exit={{opacity:0,height:0}}><div><strong>✦ English note</strong><button onClick={()=>setFeedback(null)} aria-label="关闭英语反馈">×</button></div><p>{feedback.tip}</p>{feedback.corrected_text&&<small>Try: “{feedback.corrected_text}”</small>}</motion.aside>}</AnimatePresence>
  <AnimatePresence>{error&&<motion.div className="error" role="alert" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><span>{error}</span><button onClick={()=>pending?void send(pending):void load()}>Try again</button></motion.div>}</AnimatePresence>
  <form onSubmit={submit}><label className="sr-only" htmlFor="message">Write an English reply to Emma</label><textarea id="message" maxLength={500} rows={1} value={text} onChange={e=>setText(e.target.value)} onKeyDown={keyDown} placeholder="Say something to Emma…" disabled={!ready||busy||!!pending}/><motion.button type="submit" disabled={!ready||busy||!!pending||!text.trim()} whileHover={reduce?undefined:{y:-2}} whileTap={reduce?undefined:{scale:.94}}>{busy?<span className="spinner"/>:'Send'}</motion.button><small>Enter to send · Shift+Enter for a new line</small></form>
  </section>
 </motion.section><AnimatePresence>{studio&&<CharacterStudio profile={profile} onChange={setProfile} onSave={()=>void saveProfile()} onClose={()=>setStudio(false)} saving={savingProfile} error={profileError}/>} {learningOpen&&<LearningPanel progress={learning} onClose={()=>setLearningOpen(false)}/>}</AnimatePresence></main>
}
