import {type FormEvent,type KeyboardEvent,useEffect,useRef,useState} from 'react'
import {AnimatePresence,motion,useReducedMotion} from 'motion/react'
import {ApiError,api,quotaText,session} from './api'
import {AvatarStage} from './components/AvatarStage'
import {defaultAvatar} from './avatar'
import {CharacterStudio} from './components/CharacterStudio'
import {EventCard} from './components/EventCard'
import {LearningPanel} from './components/LearningPanel'
import {StatBar} from './components/StatBar'
import type {ActiveEvent,EventUpdate,Feedback,LearningProgress,Message,Mood,NpcEntry,NpcProfile,Quota,Stats,User} from './types'
type Pending={message:string;key:string}
const initialProfile:NpcProfile={name:'Emma',relationship:'Friend',personality:['kind','thoughtful','quiet'],interests:['art','music','photography'],occupation:'Designer',longTermGoal:'Open a small independent design studio.',avatar:defaultAvatar}
export default function App({user,initialQuota,onLogout}:{user:User;initialQuota:Quota;onLogout:()=>void}){
 const reduce=useReducedMotion(),[stats,setStats]=useState<Stats|null>(null),[mood,setMood]=useState<Mood>('sad'),[messages,setMessages]=useState<Message[]>([]),[feedback,setFeedback]=useState<Feedback|null>(null),[text,setText]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Pending|null>(null),log=useRef<HTMLDivElement>(null)
 const [quota,setQuota]=useState(initialQuota)
 const [profile,setProfile]=useState<NpcProfile>(initialProfile),[studio,setStudio]=useState(false),[savingProfile,setSavingProfile]=useState(false),[profileError,setProfileError]=useState('')
 const [npcs,setNpcs]=useState<NpcEntry[]>([]),[npcId,setNpcId]=useState(localStorage.getItem('lingolife.npc-id')||'emma'),[creating,setCreating]=useState(false)
 const [language,setLanguage]=useState<'zh'|'en'>((localStorage.getItem('lingolife.language') as 'zh'|'en')||'zh'),zh=language==='zh'
 const [activeEvent,setActiveEvent]=useState<ActiveEvent|null>(null),[eventUpdate,setEventUpdate]=useState<EventUpdate|null>(null),[learning,setLearning]=useState<LearningProgress|null>(null),[learningOpen,setLearningOpen]=useState(false)
 const fail=(cause:unknown,fallback:string)=>{if(cause instanceof ApiError&&(cause.status===401||cause.status===403)){session.clear();onLogout();return}if(cause instanceof ApiError&&cause.code==='RATE_LIMITED')setError("You're sending messages quickly. Wait a minute, then try again.");else if(cause instanceof ApiError&&cause.status===429)setError("You've used today's messages. Come back tomorrow to continue with Emma.");else setError(fallback)}
 const loadNpc=async(id:string,entries?:NpcEntry[])=>{setError('');setReady(false);try{const list=entries||npcs;const chosen=list.find(x=>x.id===id)||list[0];if(!chosen)throw new Error('No character');const room=await api.room(chosen.id);setNpcId(chosen.id);localStorage.setItem('lingolife.npc-id',chosen.id);setProfile(chosen.profile);setStats(room.stats);setMood(room.npc.animation);setMessages(room.messages);setActiveEvent(room.active_event||null);setEventUpdate(null);setFeedback(null);if(room.quota)setQuota(room.quota);setReady(true)}catch(cause){fail(cause,zh?'无法打开房间，请检查网络后重试。':"Couldn't open the room. Check your connection and try again.")}}
 const load=async()=>{try{const data=await api.npcs();setNpcs(data.npcs);const id=data.npcs.some(x=>x.id===npcId)?npcId:data.npcs[0]?.id||'emma';await loadNpc(id,data.npcs);void api.learningProfile().then(setLearning).catch(()=>undefined)}catch(cause){fail(cause,zh?'无法载入角色。':'Could not load characters.')}}
 // The room is loaded once per authenticated mount; retries call load explicitly.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void load()},[])
 useEffect(()=>{log.current?.scrollTo({top:log.current.scrollHeight,behavior:reduce?'auto':'smooth'})},[messages,busy,reduce])
 const send=async(request:Pending)=>{setBusy(true);setError('');setMessages(old=>[...old,{speaker:'npc',text:''}]);try{const result=await api.chatStream(request.message,request.key,npcId,chunk=>setMessages(old=>old.map((item,index)=>index===old.length-1&&item.speaker==='npc'?{...item,text:item.text+chunk}:item)));setMessages(old=>old.map((item,index)=>index===old.length-1&&item.speaker==='npc'?{...item,text:result.npc_reply}:item));setStats(result.stats);setMood(result.animation);setFeedback(result.english_feedback);if(result.quota)setQuota(result.quota);if(result.event_update)setEventUpdate(result.event_update);if('active_event'in result)setActiveEvent(result.active_event||null);if(result.learning_summary)setLearning(result.learning_summary);setPending(null);setText('')}catch(cause){setMessages(old=>old.slice(0,-1));fail(cause,zh?'回复中断了，你的消息仍保留着，请重试。':'The reply was interrupted. Your message is safe — try again.')}finally{setBusy(false)}}
 const submit=(event:FormEvent)=>{event.preventDefault();const message=text.trim();if(!message||busy||pending||!ready)return;const request={message,key:api.key()};setPending(request);setMessages(old=>[...old,{speaker:'player',text:message}]);void send(request)}
 const keyDown=(event:KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();event.currentTarget.form?.requestSubmit()}}
 const saveProfile=async()=>{setSavingProfile(true);setProfileError('');try{const saved=creating?await api.createNpc({...profile,avatar:{...profile.avatar,strokes:[]}}):await api.saveNpc(npcId,{...profile,avatar:{...profile.avatar,strokes:[]}});const data=await api.npcs();setNpcs(data.npcs);setCreating(false);setStudio(false);await loadNpc(saved.id,data.npcs)}catch(cause){setProfileError(cause instanceof ApiError&&cause.code==='NPC_LIMIT_REACHED'?(zh?'最多只能创建5个角色。':'You can create up to five characters.'):(zh?'无法保存角色，请重试。':'Could not save this character.'))}finally{setSavingProfile(false)}}
 return <main className="shell"><motion.section className="room" initial={reduce?false:{opacity:0,y:12}} animate={{opacity:1,y:0}}>
  <header><div><p className="eyebrow">{profile.name}{zh?'的房间':"'s room"}</p><h1>{activeEvent?.title||(zh?'安静的夜晚':'A quiet evening')}</h1></div><div className="account"><select className="npc-switch" value={npcId} disabled={busy} onChange={e=>void loadNpc(e.target.value)} aria-label={zh?'切换角色':'Switch character'}>{npcs.map(x=><option key={x.id} value={x.id}>{x.profile.name}</option>)}</select><button disabled={npcs.length>=5} onClick={()=>{setCreating(true);setProfile({...initialProfile,name:zh?'新角色':'New character',avatar:{...defaultAvatar,strokes:[]}});setStudio(true)}}>＋ {zh?'新角色':'New'}</button><button className="learn-button" onClick={()=>setLearningOpen(true)}>◒ {zh?'进度':'Progress'}</button><button className="create-button" onClick={()=>{setCreating(false);setStudio(true)}}>✦ {zh?'编辑':'Customize'}</button><select value={language} onChange={e=>{const next=e.target.value as 'zh'|'en';setLanguage(next);localStorage.setItem('lingolife.language',next)}} aria-label="界面语言"><option value="zh">中文</option><option value="en">English</option></select><span><b>{user.username}</b><small>{quotaText(quota)}</small></span><button onClick={async()=>{try{await api.logout()}finally{session.clear();onLogout()}}}>{zh?'退出':'Exit'}</button></div></header>
  <StatBar stats={stats}/><AvatarStage mood={mood} avatar={profile.avatar}/>
  <section className="conversation" aria-label={`Conversation with ${profile.name}`}><EventCard language={language} event={activeEvent} update={eventUpdate}/><div className="messages" ref={log} role="log" aria-live="polite">
   {!ready&&!error&&<p className="empty">Opening the door…</p>}
   <AnimatePresence initial={false}>{messages.map((item,index)=><motion.article className={`message comic-message ${item.speaker}`} key={index} initial={reduce?false:{opacity:0,y:22,scale:.82,filter:'blur(8px)'}} animate={{opacity:1,y:0,scale:1,filter:'blur(0px)'}} transition={{type:'spring',stiffness:330,damping:25,mass:.72}}>{item.speaker==='npc'&&<span className="avatar" aria-hidden>{profile.name[0]||'N'}</span>}<div className="bubble comic-bubble">{item.speaker==='npc'&&<b>{profile.name}</b>}<p>{item.text.split('').map((char,charIndex)=><motion.span key={charIndex} initial={reduce?false:{opacity:0,y:3,filter:'blur(3px)'}} animate={{opacity:1,y:0,filter:'blur(0px)'}} transition={{duration:.22}}>{char}</motion.span>)}</p>{busy&&index===messages.length-1&&!item.text&&<span className="typing" aria-label={`${profile.name} is typing`}><i/><i/><i/></span>}</div></motion.article>)}</AnimatePresence>
  </div>
  <AnimatePresence>{feedback&&<motion.aside className="feedback" initial={reduce?false:{opacity:0,y:8,height:0}} animate={{opacity:1,y:0,height:'auto'}} exit={{opacity:0,height:0}}><div><strong>✦ {zh?'英语提示':'English note'}</strong><button onClick={()=>setFeedback(null)} aria-label="关闭英语反馈">×</button></div><p>{feedback.tip}</p>{feedback.corrected_text&&<small>{zh?'建议表达':'Try'}: “{feedback.corrected_text}”</small>}</motion.aside>}</AnimatePresence>
  <AnimatePresence>{error&&<motion.div className="error" role="alert" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><span>{error}</span><button onClick={()=>pending?void send(pending):void load()}>Try again</button></motion.div>}</AnimatePresence>
  <form onSubmit={submit}><label className="sr-only" htmlFor="message">Write an English reply</label><textarea id="message" maxLength={500} rows={1} value={text} onChange={e=>setText(e.target.value)} onKeyDown={keyDown} placeholder={zh?`用英语和 ${profile.name} 聊聊…`:`Say something to ${profile.name}…`} disabled={!ready||busy||!!pending}/><motion.button type="submit" disabled={!ready||busy||!!pending||!text.trim()} whileHover={reduce?undefined:{y:-2}} whileTap={reduce?undefined:{scale:.94}}>{busy?<span className="spinner"/>:(zh?'发送':'Send')}</motion.button><small>{zh?'Enter 发送 · Shift+Enter 换行':'Enter to send · Shift+Enter for a new line'}</small></form>
  </section>
 </motion.section><AnimatePresence>{studio&&<CharacterStudio language={language} profile={profile} onChange={setProfile} onSave={()=>void saveProfile()} onClose={()=>{setStudio(false);if(creating){setCreating(false);const current=npcs.find(x=>x.id===npcId);if(current)setProfile(current.profile)}}} saving={savingProfile} error={profileError}/>} {learningOpen&&<LearningPanel progress={learning} onClose={()=>setLearningOpen(false)}/>}</AnimatePresence></main>
}
