import {createContext,createElement,useContext,useEffect,useMemo,useState,type ReactNode} from 'react'

export type Language='zh'|'en'

const STORAGE_KEY='lingolife.language'

export const messages={
 zh:{
  'common.close':'关闭','common.cancel':'取消','common.save':'保存','common.saving':'保存中…','common.retry':'重试','common.loading':'加载中…','common.comingSoon':'即将推出',
  'auth.title':'进入 LingoLife','auth.subtitle':'使用邀请码创建你的唯一身份','auth.username':'用户名','auth.usernamePlaceholder':'输入唯一用户名','auth.password':'密码','auth.passwordPlaceholder':'任意格式，区分大小写','auth.login':'登录','auth.register':'邀请码注册','auth.loginTitle':'欢迎回来','auth.loginSubtitle':'登录后继续你的城市、角色和故事。','auth.loginAction':'登录并进入城市','auth.invite':'邀请码','auth.invitePlaceholder':'输入邀请码','auth.enter':'进入城市','auth.entering':'正在进入…','auth.error':'无法进入，请检查用户名和邀请码。','auth.invalidCredentials':'用户名或密码错误。','auth.passwordStored':'密码只会以不可逆安全哈希保存。',
  'nav.newCharacter':'新角色','nav.progress':'进度','nav.customize':'编辑','nav.settings':'设置','nav.logout':'退出','nav.switchCharacter':'切换角色','nav.quota':'今日剩余 {{count}} 条消息',
  'stats.bond':'关系','stats.mood':'心情','stats.english':'英语经验',
  'settings.title':'设置','settings.subtitle':'按照你的方式体验 LingoLife','settings.general':'通用','settings.language':'界面语言','settings.languageHint':'更改系统界面、按钮和提示的显示语言；角色对话仍保持英文。','settings.chinese':'简体中文','settings.english':'English','settings.account':'账号与密码','settings.passwordHint':'修改密码后，其他设备会自动退出；当前设备保持登录。','settings.legacyPasswordHint':'这是内测期间创建的旧账号。设置一次密码后即可在其他设备登录。','settings.password':'设置密码','settings.currentPassword':'当前密码','settings.newPassword':'新密码','settings.confirmPassword':'确认新密码','settings.savePassword':'保存密码','settings.passwordMismatch':'两次输入的密码不一致。','settings.currentPasswordWrong':'当前密码不正确。','settings.passwordSaved':'密码已保存，现在可以在其他设备登录。','settings.future':'更多设置','settings.futureHint':'声音、动画和辅助功能将在这里提供。',
  'map.title':'LingoLife 城市','map.subtitle':'看看朋友们今天在哪里','map.home':'{{name}}的家','map.currentLocation':'当前位置','map.openCharacter':'和 {{name}} 聊天','map.zoomIn':'放大地图','map.zoomOut':'缩小地图','map.resetView':'重置视图','map.empty':'创建你的第一个角色，点亮城市中的一处新家。','map.back':'返回城市','map.todayAt':'今天在{{place}}','map.location.home':'家','map.location.cafe':'咖啡馆','map.location.park':'公园','map.location.library':'图书馆','map.location.office':'工作区','map.location.market':'商业街','map.location.station':'车站','map.location.riverside':'河畔',
  'room.title':'{{name}}的房间','room.quietEvening':'安静的夜晚','room.opening':'正在打开门…','room.conversationLabel':'与 {{name}} 的对话',
  'chat.placeholder':'用英语和 {{name}} 聊聊…','chat.send':'发送','chat.sendHint':'Enter 发送 · Shift+Enter 换行','chat.inputLabel':'输入英文回复','chat.typing':'{{name}} 正在输入','chat.feedback':'英语提示','chat.suggestion':'建议表达','chat.showHistory':'展开更早的 {{count}} 条记录','chat.hideHistory':'收起更早记录','chat.retry':'再试一次','chat.loadError':'无法打开会话，请检查网络后重试。','chat.streamError':'回复中断了，你的消息仍保留着，请重试。','chat.rateLimited':'你发送得有点快，请稍等一分钟再试。','chat.quotaReached':'今天的消息额度已用完，明天再继续吧。',
  'event.today':'今日故事','event.yourMoment':'你的时刻','event.complete':'故事完成','event.memoryMade':'留下了记忆 ✦','event.remember':'值得记住的一刻','event.defaultOutcome':'你的回应改变了故事结局。',
  'learning.eyebrow':'英语旅程','learning.title':'你已经掌握的能力','learning.preparing':'学习档案正在准备中。自然地聊下去，每个有用的表达都会逐渐显现。','learning.overall':'总体','learning.mastered':'已掌握 {{mastered}} / {{total}} 项能力','learning.explanation':'能力来自真实使用，而不是单次评分；需要复习时，掌握度会缓慢下降。','learning.recommended':'下一步推荐','learning.recommendedHint':'试着在今天的故事中自然使用这些表达。','learning.successUses':'成功使用 {{count}} 次','learning.vocabulary':'词汇库 · {{count}} 个词','learning.howItWorks':'进步方式','learning.progressCycle':'接触表达 → 成功使用 → 过段时间再次复习。持续且有意义的使用会带来真正掌握。',
  'character.studio':'NPC 角色工作室','character.title':'创造一个值得了解的人','character.identity':'身份设定','character.appearance':'外观','character.name':'名字','character.relationship':'关系（自由填写）','character.occupation':'职业（自由填写）','character.personality':'性格（逗号分隔，最多4项）','character.interests':'兴趣（逗号分隔，最多5项）','character.goal':'长期目标','character.skin':'肤色','character.hairColor':'发色','character.outfitColor':'服装颜色','character.influence':'你的设定会影响未来的记忆和事件。','character.save':'保存角色','character.newName':'新角色','character.limit':'最多只能创建5个角色。','character.saveError':'无法保存角色，请重试。','character.loadError':'无法载入角色。',
  'error.generic':'出了点问题，请稍后重试。','error.network':'网络连接异常，请稍后重试。','error.unauthorized':'登录已失效，请重新进入。'
 },
 en:{
  'common.close':'Close','common.cancel':'Cancel','common.save':'Save','common.saving':'Saving…','common.retry':'Try again','common.loading':'Loading…','common.comingSoon':'Coming soon',
  'auth.title':'Enter LingoLife','auth.subtitle':'Create your unique identity with an invite code','auth.username':'Username','auth.usernamePlaceholder':'Choose a unique username','auth.password':'Password','auth.passwordPlaceholder':'Any format, case-sensitive','auth.login':'Sign in','auth.register':'Create account','auth.loginTitle':'Welcome back','auth.loginSubtitle':'Continue your city, characters, and stories on any device.','auth.loginAction':'Sign in to the city','auth.invite':'Invite code','auth.invitePlaceholder':'Enter your invite code','auth.enter':'Enter the city','auth.entering':'Entering…','auth.error':'Could not enter. Check your username and invite code.','auth.invalidCredentials':'Username or password is incorrect.','auth.passwordStored':'Passwords are stored only as irreversible secure hashes.',
  'nav.newCharacter':'New character','nav.progress':'Progress','nav.customize':'Customize','nav.settings':'Settings','nav.logout':'Exit','nav.switchCharacter':'Switch character','nav.quota':'{{count}} messages left today',
  'stats.bond':'Bond','stats.mood':'Mood','stats.english':'English XP',
  'settings.title':'Settings','settings.subtitle':'Make LingoLife feel right for you','settings.general':'General','settings.language':'Interface language','settings.languageHint':'Changes the language of system screens, buttons, and guidance. Character conversations remain in English.','settings.chinese':'简体中文','settings.english':'English','settings.account':'Account & password','settings.passwordHint':'Changing your password signs out other devices while keeping this one signed in.','settings.legacyPasswordHint':'This account was created during early beta. Set a password once to sign in on other devices.','settings.password':'Set password','settings.currentPassword':'Current password','settings.newPassword':'New password','settings.confirmPassword':'Confirm new password','settings.savePassword':'Save password','settings.passwordMismatch':'The two passwords do not match.','settings.currentPasswordWrong':'The current password is incorrect.','settings.passwordSaved':'Password saved. You can now sign in on other devices.','settings.future':'More settings','settings.futureHint':'Sound, motion, and accessibility options will live here.',
  'map.title':'LingoLife City','map.subtitle':'See where your friends are today','map.home':"{{name}}'s home",'map.currentLocation':'Current location','map.openCharacter':'Talk with {{name}}','map.zoomIn':'Zoom in','map.zoomOut':'Zoom out','map.resetView':'Reset view','map.empty':'Create your first character to light up a new home in the city.','map.back':'Back to city','map.todayAt':'At {{place}} today','map.location.home':'Home','map.location.cafe':'Café','map.location.park':'Park','map.location.library':'Library','map.location.office':'Work district','map.location.market':'Shopping street','map.location.station':'Station','map.location.riverside':'Riverside',
  'room.title':"{{name}}'s room",'room.quietEvening':'A quiet evening','room.opening':'Opening the door…','room.conversationLabel':'Conversation with {{name}}',
  'chat.placeholder':'Say something to {{name}} in English…','chat.send':'Send','chat.sendHint':'Enter to send · Shift+Enter for a new line','chat.inputLabel':'Write an English reply','chat.typing':'{{name}} is typing','chat.feedback':'English note','chat.suggestion':'Try','chat.showHistory':'Show {{count}} earlier messages','chat.hideHistory':'Hide earlier messages','chat.retry':'Try again','chat.loadError':"Couldn't open the conversation. Check your connection and try again.",'chat.streamError':'The reply was interrupted. Your message is safe — try again.','chat.rateLimited':"You're sending messages quickly. Wait a minute, then try again.",'chat.quotaReached':"You've used today's messages. Come back tomorrow to continue.",
  'event.today':"Today's story",'event.yourMoment':'Your moment','event.complete':'Story complete','event.memoryMade':'Memory made ✦','event.remember':'A moment to remember','event.defaultOutcome':'Your response changed how this story ended.',
  'learning.eyebrow':'English journey','learning.title':'What you can do','learning.preparing':'Your learning profile is getting ready. Keep talking naturally and each useful expression will become visible here.','learning.overall':'overall','learning.mastered':'{{mastered}} of {{total}} skills mastered','learning.explanation':'Mastery grows from successful use, not from a single score. Skills gently fade when they need review.','learning.recommended':'Recommended next','learning.recommendedHint':"Try using these naturally in today's story.",'learning.successUses':'{{count}} successful uses','learning.vocabulary':'Vocabulary bank · {{count}} words','learning.howItWorks':'How progress works','learning.progressCycle':'Meet an expression → use it successfully → revisit it later. Repeated, meaningful use moves a skill toward mastery.',
  'character.studio':'NPC agent studio','character.title':'Create someone worth knowing','character.identity':'Identity','character.appearance':'Appearance','character.name':'Name','character.relationship':'Relationship (custom)','character.occupation':'Occupation (custom)','character.personality':'Personality (comma-separated, up to 4)','character.interests':'Interests (comma-separated, up to 5)','character.goal':'Long-term dream','character.skin':'Skin tone','character.hairColor':'Hair color','character.outfitColor':'Outfit color','character.influence':'Your choices shape future memories and events.','character.save':'Save character','character.newName':'New character','character.limit':'You can create up to five characters.','character.saveError':'Could not save this character.','character.loadError':'Could not load characters.',
  'error.generic':'Something went wrong. Please try again later.','error.network':'There is a network problem. Please try again.','error.unauthorized':'Your session has expired. Please enter again.'
 }
} as const

export type TranslationKey=keyof typeof messages.zh
type Variables=Record<string,string|number>
type LanguageContextValue={language:Language;setLanguage:(language:Language)=>void;t:(key:TranslationKey,variables?:Variables)=>string}

const LanguageContext=createContext<LanguageContextValue|undefined>(undefined)
const storedLanguage=():Language=>{try{return localStorage.getItem(STORAGE_KEY)==='en'?'en':'zh'}catch{return 'zh'}}
const format=(template:string,variables?:Variables)=>template.replace(/\{\{(\w+)\}\}/g,(_,key:string)=>String(variables?.[key]??`{{${key}}}`))

export function LanguageProvider({children}:{children:ReactNode}){
 const [language,setLanguageState]=useState<Language>(storedLanguage)
 const setLanguage=(next:Language)=>{setLanguageState(next);try{localStorage.setItem(STORAGE_KEY,next)}catch{/* Storage can be unavailable in private contexts. */}}
 useEffect(()=>{document.documentElement.lang=language==='zh'?'zh-CN':'en'},[language])
 const value=useMemo<LanguageContextValue>(()=>({language,setLanguage,t:(key,variables)=>format(messages[language][key],variables)}),[language])
 return createElement(LanguageContext.Provider,{value},children)
}

export function useLanguage(){const value=useContext(LanguageContext);if(!value)throw new Error('useLanguage must be used inside LanguageProvider');return value}
