import {motion,useReducedMotion} from 'motion/react'
import type {CSSProperties} from 'react'
import type {LearningProgress} from '../types'
import {useLanguage} from '../i18n'

export function LearningPanel({progress,onClose}:{progress:LearningProgress|null;onClose:()=>void}){
 const reduce=useReducedMotion(),{t,language}=useLanguage(),zh=language==='zh'
 const targetNames:Record<string,string>={'intent.follow_up':'追问细节','intent.empathy':'表达共情','intent.advice':'给出温和建议','intent.past_story':'描述过去的事情','grammar.past_simple':'一般过去时','grammar.questions':'自然地提问','grammar.soft_advice':'委婉建议句式','grammar.sequence':'按顺序讲述故事'}
 const categories:Record<string,string>={feelings:'情绪感受',work_school:'工作与学习',relationships:'人际关系',daily_life:'日常生活',story_actions:'故事动作',personality:'性格特征',conversation:'会话表达',goals_growth:'目标与成长',places_travel:'地点与旅行',health_wellbeing:'健康与身心'}
 const name=(id:string,fallback:string)=>zh?(targetNames[id]||fallback):fallback,status=(value?:string)=>zh?({new:'未开始',learning:'学习中',mastered:'已掌握'}[value||'new']||value):value||'new',kind=(value:string)=>zh?({intent:'沟通能力',grammar:'语法能力'}[value]||value):value,level=(value:string)=>zh?({'A2 foundation':'A2 基础','A2+':'A2 进阶','B1-ready':'接近 B1'}[value]||value):value
 return <motion.div className="learning-backdrop" initial={reduce?false:{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><section className="learning-panel" role="dialog" aria-modal="true"><header><div><p className="eyebrow">{t('learning.eyebrow')}</p><h2>{t('learning.title')}</h2></div><button onClick={onClose} aria-label={t('common.close')}>×</button></header>{!progress?<p className="learning-empty">{t('learning.preparing')}</p>:<><div className="learning-hero"><div className="mastery-ring" style={{'--mastery':`${progress.overall_mastery*3.6}deg`} as CSSProperties}><strong>{progress.overall_mastery}%</strong><small>{t('learning.overall')}</small></div><div><span>{level(progress.level)}</span><h3>{t('learning.mastered',{mastered:progress.mastered_count,total:progress.total_targets})}</h3><p>{t('learning.explanation')}</p></div></div>{progress.recommended.length>0&&<aside className="recommended"><strong>{t('learning.recommended')}</strong><p>{t('learning.recommendedHint')}</p><div>{progress.recommended.map(item=><span key={item.id}>{name(item.id,item.name)}</span>)}</div></aside>}<div className="skill-list">{progress.targets.map((target,index)=><motion.article key={target.id} initial={reduce?false:{opacity:0,x:8}} animate={{opacity:1,x:0}} transition={{delay:index*.035}}><div><i className={`skill-state ${target.status||'new'}`}/><span><strong>{name(target.id,target.name)}</strong><small>{kind(target.kind)} · {status(target.status)}{target.successes?` · ${t('learning.successUses',{count:target.successes})}`:''}</small></span><b>{target.mastery}%</b></div><div className="skill-meter"><i style={{width:`${target.mastery}%`}}/></div></motion.article>)}</div>{progress.vocabulary&&<aside className="recommended vocabulary-bank"><strong>{t('learning.vocabulary',{count:Object.values(progress.vocabulary).flat().length})}</strong><div>{Object.entries(progress.vocabulary).map(([category,words])=><details key={category}><summary>{zh?(categories[category]||category):category.replaceAll('_',' ')}</summary><p>{words.join(' · ')}</p></details>)}</div></aside>}<footer><strong>{t('learning.howItWorks')}</strong><p>{t('learning.progressCycle')}</p></footer></>}</section></motion.div>
}
