import {motion,useReducedMotion} from 'motion/react'
import type {CSSProperties} from 'react'
import type {LearningProgress} from '../types'
import {useLanguage} from '../i18n'

export function LearningPanel({progress,onClose}:{progress:LearningProgress|null;onClose:()=>void}){
 const reduce=useReducedMotion(),{t}=useLanguage()
 return <motion.div className="learning-backdrop" initial={reduce?false:{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><section className="learning-panel" role="dialog" aria-modal="true"><header><div><p className="eyebrow">{t('learning.eyebrow')}</p><h2>{t('learning.title')}</h2></div><button onClick={onClose} aria-label={t('common.close')}>×</button></header>{!progress?<p className="learning-empty">{t('learning.preparing')}</p>:<><div className="learning-hero"><div className="mastery-ring" style={{'--mastery':`${progress.overall_mastery*3.6}deg`} as CSSProperties}><strong>{progress.overall_mastery}%</strong><small>{t('learning.overall')}</small></div><div><span>{progress.level}</span><h3>{t('learning.mastered',{mastered:progress.mastered_count,total:progress.total_targets})}</h3><p>{t('learning.explanation')}</p></div></div>{progress.recommended.length>0&&<aside className="recommended"><strong>{t('learning.recommended')}</strong><p>{t('learning.recommendedHint')}</p><div>{progress.recommended.map(item=><span key={item.id}>{item.name}</span>)}</div></aside>}<div className="skill-list">{progress.targets.map((target,index)=><motion.article key={target.id} initial={reduce?false:{opacity:0,x:8}} animate={{opacity:1,x:0}} transition={{delay:index*.035}}><div><i className={`skill-state ${target.status||'new'}`}/><span><strong>{target.name}</strong><small>{target.kind} · {target.status||'new'}{target.successes?` · ${t('learning.successUses',{count:target.successes})}`:''}</small></span><b>{target.mastery}%</b></div><div className="skill-meter"><i style={{width:`${target.mastery}%`}}/></div></motion.article>)}</div>{progress.vocabulary&&<aside className="recommended vocabulary-bank"><strong>{t('learning.vocabulary',{count:Object.values(progress.vocabulary).flat().length})}</strong><div>{Object.entries(progress.vocabulary).map(([category,words])=><details key={category}><summary>{category.replaceAll('_',' ')}</summary><p>{words.join(' · ')}</p></details>)}</div></aside>}<footer><strong>{t('learning.howItWorks')}</strong><p>{t('learning.progressCycle')}</p></footer></>}</section></motion.div>
}
