import {type FormEvent,useEffect,useRef,useState} from 'react'
import {ApiError,api} from '../api'
import {useLanguage,type Language} from '../i18n'
import './SettingsPanel.css'
import './AccountSettings.css'

type Props={onClose:()=>void;hasPassword:boolean;onPasswordSet:()=>void}

export function SettingsPanel({onClose,hasPassword,onPasswordSet}:Props){
 const {language,setLanguage,t}=useLanguage(),closeRef=useRef<HTMLButtonElement>(null)
 const [currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmation,setConfirmation]=useState('')
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false)
 useEffect(()=>{closeRef.current?.focus();const close=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose()};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[onClose])
 const option=(value:Language,label:string,detail:string)=><label className={`settings-language-option ${language===value?'selected':''}`}><input type="radio" name="interface-language" value={value} checked={language===value} onChange={()=>setLanguage(value)}/><span aria-hidden>{language===value?'✓':''}</span><b>{label}</b><small>{detail}</small></label>
 const savePassword=async(event:FormEvent)=>{event.preventDefault();setError('');setSuccess(false);if(newPassword!==confirmation){setError(t('settings.passwordMismatch'));return}setBusy(true);try{await api.setPassword(newPassword,hasPassword?currentPassword:undefined);setCurrentPassword('');setNewPassword('');setConfirmation('');setSuccess(true);onPasswordSet()}catch(cause){setError(cause instanceof ApiError&&cause.code==='INVALID_CURRENT_PASSWORD'?t('settings.currentPasswordWrong'):t('error.generic'))}finally{setBusy(false)}}
 return <div className="settings-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><section className="settings-panel" role="dialog" aria-modal="true" aria-labelledby="settings-title"><header><div><p>{t('settings.general')}</p><h2 id="settings-title">{t('settings.title')}</h2><span>{t('settings.subtitle')}</span></div><button ref={closeRef} type="button" onClick={onClose} aria-label={t('common.close')}>×</button></header><div className="settings-groups"><section className="settings-group"><div className="settings-group-heading"><span className="settings-icon" aria-hidden>文</span><div><h3>{t('settings.language')}</h3><p>{t('settings.languageHint')}</p></div></div><div className="settings-language-options">{option('zh',t('settings.chinese'),'中文')}{option('en',t('settings.english'),'English')}</div></section><section className="settings-group"><div className="settings-group-heading"><span className="settings-icon" aria-hidden>钥</span><div><h3>{t('settings.account')}</h3><p>{hasPassword?t('settings.passwordHint'):t('settings.legacyPasswordHint')}</p></div></div><form className="settings-password-form" onSubmit={savePassword}>{hasPassword&&<label>{t('settings.currentPassword')}<input required maxLength={256} type="password" autoComplete="current-password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)}/></label>}<label>{t(hasPassword?'settings.newPassword':'settings.password')}<input required maxLength={256} type="password" autoComplete="new-password" value={newPassword} onChange={event=>setNewPassword(event.target.value)}/></label><label>{t('settings.confirmPassword')}<input required maxLength={256} type="password" autoComplete="new-password" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label>{error&&<p className="settings-password-error" role="alert">{error}</p>}{success&&<p className="settings-password-success" role="status">{t('settings.passwordSaved')}</p>}<button disabled={busy}>{busy?t('common.saving'):t('settings.savePassword')}</button></form></section><section className="settings-group settings-future" aria-disabled="true"><div className="settings-group-heading"><span className="settings-icon" aria-hidden>＋</span><div><h3>{t('settings.future')} <small>{t('common.comingSoon')}</small></h3><p>{t('settings.futureHint')}</p></div></div></section></div></section></div>
}
